bug:
  - "\\bbug\\b"

enhancement:
  - "\\bfeature\\b"
  - "\\benhancement\\b"

question:
  - "\\bquestion\\b"
  - "\\bhelp\\b"

documentation:
  - "\\bdocs?\\b"
  - "\\breadme\\b"

dependencies:
  - "\\bdependenc(y|ies)\\b"
  - "\\bpackage\\b"

security:
  - "\\bsecurity\\b"
  - "\\bvulnerability\\b"