bug:
  - '(?i)\b(bug|error|broken|crash|problem)\b'

enhancement:
  - '(?i)\b(feature|enhancement|improvement|request)\b'

question:
  - '(?i)\b(how|what|when|where|why|help|question)\b'

documentation:
  - '(?i)\b(doc|documentation|typo|example|readme)\b'

dependencies:
  - '(?i)\b(dependency|dependencies|package|version|update|upgrade)\b'

security:
  - '(?i)\b(security|vulnerability|exploit|attack|cve)\b'