# Add 'bug' label to any issue containing the word 'bug'
bug: '(bug|error|broken|crash|problem)'

# Add 'enhancement' label to any issue containing these words
enhancement: '(feature|enhancement|improvement|request)'

# Add 'question' label to any issue containing these words
question: '(how|what|when|where|why|help)'

# Add 'documentation' label to any issue containing these words
documentation: '(doc|documentation|typo|example|readme)'

# Add 'dependencies' label to any issue containing these words
dependencies: '(dependency|package|version|update|upgrade)'

# Add 'security' label to any issue containing these words
security: '(security|vulnerability|exploit|attack|cve)'