# Issue type labels
bug:
  - 'bug'
  - 'error'
  - 'not working'
  - 'broken'
  - 'crash'
  - 'problem'

enhancement:
  - 'feature'
  - 'enhancement'
  - 'improvement'
  - 'request'
  - 'add'

question:
  - 'how'
  - 'what'
  - 'when'
  - 'where'
  - 'why'
  - 'question'
  - 'help'

documentation:
  - 'doc'
  - 'typo'
  - 'example'
  - 'readme'

dependencies:
  - 'dependency'
  - 'package'
  - 'version'
  - 'update'
  - 'upgrade'

security:
  - 'security'
  - 'vulnerability'
  - 'exploit'
  - 'attack'
  - 'cve'