bug:
  - '\b(bug|error|broken|crash|problem)\b'
enhancement:
  - '\b(feature|enhancement|improvement|request)\b'
question:
  - '\b(how|what|when|where|why|help|question)\b'
documentation:
  - '\b(doc|documentation|typo|example|readme)\b'
dependencies:
  - '\b(dependency|dependencies|package|version|update|upgrade)\b'
security:
  - '\b(security|vulnerability|exploit|attack|cve)\b'