bug:
  - "\\bbug\\b"
  - "\\berror\\b"
  - "not working"
  - "\\bbroken\\b"
  - "\\bcrash\\b"
  - "\\bproblem\\b"

enhancement:
  - "\\bfeature\\b"
  - "\\benhancement\\b"
  - "\\bimprovement\\b"
  - "\\brequest\\b"
  - "\\badd\\b"

question:
  - "\\bhow\\b"
  - "\\bwhat\\b"
  - "\\bwhen\\b"
  - "\\bwhere\\b"
  - "\\bwhy\\b"
  - "\\bquestion\\b"
  - "\\bhelp\\b"

documentation:
  - "\\bdoc\\b"
  - "\\btypo\\b"
  - "\\bexample\\b"
  - "\\breadme\\b"

dependencies:
  - "\\bdependency\\b"
  - "\\bpackage\\b"
  - "\\bversion\\b"
  - "\\bupdate\\b"
  - "\\bupgrade\\b"

security:
  - "\\bsecurity\\b"
  - "\\bvulnerability\\b"
  - "\\bexploit\\b"
  - "\\battack\\b"
  - "\\bcve\\b"