bug:
  - '(?i).*bug.*'
enhancement:
  - '(?i).*feature.*'
  - '(?i).*enhancement.*'
question:
  - '(?i).*how.*'
  - '(?i).*what.*'
  - '(?i).*help.*'
documentation:
  - '(?i).*doc.*'
  - '(?i).*readme.*'
dependencies:
  - '(?i).*dependency.*'
  - '(?i).*package.*'
security:
  - '(?i).*security.*'
  - '(?i).*vulnerability.*'
