name: CI - Run Scraper Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      # General config
      DATA_DIR: data
      CONFIG_DIR: config
      DEBUG: "false"
      SOURCE_PAGE: https://amd64.origin.releases.ci.openshift.org/releasestream/4-scos-stable/release/4.19.0-okd-scos.0
      GITHUB_API_URL: https://api.github.com/graphql
      GITHUB_SERVER: https://github.com
      JIRA_SERVER: https://issues.redhat.com  
      LLM_MODEL: mistral
      LLM_API_URL: http://localhost:11434/api/generate
      CONFIG_FILE_PATH: config/filter.json
      SOURCES: '["JIRA", "GITHUB"]'
      
      # Secure token passed directly (not echoed, not saved in file)
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests
