name: AI Issue Triage

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Issue Labeler
        uses: github/issue-labeler@v3.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 1
          include-title: 1