name: "Issue Labeler"
on:
  issues:
    types: 
      - opened
      - reopened
      - edited

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/issue-labeler@v3.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
          enable-versioned-regex: false
          include-title: true
          include-body: true
