name: "Test Slack Simple"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check Slack Configuration
        run: |
          if [ -z "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            echo "❌ SLACK_WEBHOOK_URL secret is not set"
            echo "Please add your Slack webhook URL to repository secrets"
            echo "Go to: Settings → Secrets and variables → Actions → New repository secret"
            echo "Name: SLACK_WEBHOOK_URL"
            echo "Value: Your Slack webhook URL (starts with https://hooks.slack.com/services/)"
            exit 1
          else
            echo "✅ SLACK_WEBHOOK_URL secret is configured"
            echo "Webhook URL starts with: $(echo '${{ secrets.SLACK_WEBHOOK_URL }}' | cut -c1-20)..."
          fi

      - name: Test Slack Webhook
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL || '#github-issues' }}",
              "text": "🧪 Test: Slack webhook is working! This is a simple test message from GitHub Actions."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
