name: "Test Slack Simple"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Test Slack Webhook
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL || '#github-issues' }}",
              "text": "🧪 Test: Slack webhook is working! This is a simple test message."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
