name: Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  models: read

jobs:
  welcome:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' && github.event.sender.type == 'User'
    steps:
      - name: Generate welcome message
        uses: actions/ai-inference@v1
        id: ai
        with:
          prompt: |
            Generate a welcoming message for a new contributor who just ${{ github.event_name == 'issues' && 'opened an issue' || 'submitted a pull request' }}.
            
            Include:
            1. Thank them for their contribution
            2. Point them to CONTRIBUTING.md and our Code of Conduct
            3. Explain our issue/PR review process
            4. Offer help if they need it
            
            Keep it friendly and encouraging!
          model: openai/gpt-4o-mini
          temperature: 0.7

      - name: Post welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            const message = `${{ steps.ai.outputs.response }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number || github.event.pull_request.number }},
              body: message
            });
